# Generated by Django 3.0.6 on 2020-06-04 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название Книги')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание книги ')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.Genre', verbose_name='Жанр Книги')),
            ],
        ),
    ]
